### ISSUE TITLE
/js/ statt /piwik.js als Default (Page-Speed-Optimierung, Caching etc.)

### ISSUE THREAD

**Issue by michelbalzer** [menatwork-ia/PiwikTrackingTag#1]
Ich stolperte über dies hier: http://www.smart-webentwicklung.de/2012/05/piwik-asynchrones-tracking-caching-probleme/

Kann man das als Standard in den nächsten Versionen eintragen?

Kern der Sache: statt /piwik.js die JavaScript-Datei durch /js/ einbinden.

Ist nur als Anregung gedacht, zur Not kann man sich das ja immer noch über's Template zurechtstückeln.

**Comment by andreasisaak** [comment]
Danke für die Info. In 16caa81fe10475faf8ec1bc451bda0c553f98583 eingebaut
